version: "3.7"  # optional since v1.27.0
services:
  web:
    build: ./web
    ports:
      - 80:80
    image: weihlin/web:test-1
  api:
    build: ./express
    ports:
      - 3001:3001
    environment:
      - DATA_PATH=csv
    image: weihlin/api:test-1
    